os: linux
language: android
jdk: oraclejdk8
notifications:
  email: gleydsonsr@gmail.com
node_js:
  - '8.10.0'
cache:
  - yarn: true
  directories:
    - node_modules
install:
  - yarn

script: yarn ci
