os: linux
language: node_js
notifications:
  email: gleydsonsr@gmail.com
node_js:
  - '8.10.0'
cache:
  directories:
    - node_modules
before_install:
  - nvm install && nvm use
install:
  - yarn

script: yarn ci
