os: linux
language: node_js
node_js:
  - '8.10.0'
cache:
  directories:
    - node_modules
before_install:
  - nvm install && nvm use
after_success:
  - snyk monitor
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search
install:
  - yarn
script: yarn ci
