os: linux
language: node_js
node_js:
  - '8.10.0'
cache:
  directories:
    - node_modules
before_install:
  - nvm install && nvm use
after_success:
  - snyk monitor
  - bash <(curl -s https://codecov.io/bash)
install:
  - yarn
script: yarn test:lint
