codecov:
  token: 79a4d82b-158f-46a2-9c0c-14dca5186cc5

coverage:
  precision: 2
  round: up
  range: "80...100"

  status:
    project:
      default:
        target: auto
        threshold: null
        base: auto
        branches: null
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        flags: null
        paths: null

    patch:
      default:
        target: auto
        base: auto
        threshold: 5%
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

    changes:
      default:
        target: auto
        base: auto
        branches: null
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        flags: null
        paths: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  require_changes: false
  behavior: default